import request from "supertest";
import {beforeAll,afterAll,describe,expect,it} from "vitest";
import {app} from "../src/app.js";
import {prisma} from "../src/config/prisma.js";
import sharp from "sharp";

let aisha:request.Agent,rohan:request.Agent,privateSlug:string,publicSlug:string;
beforeAll(async()=>{
  aisha=request.agent(app);rohan=request.agent(app);
  expect((await aisha.post("/api/v1/auth/login").send({email:"aisha@completeit.local",password:"CompleteIt@123"})).status).toBe(200);
  expect((await rohan.post("/api/v1/auth/login").send({email:"rohan@completeit.local",password:"CompleteIt@123"})).status).toBe(200);
  const p=await prisma.product.findMany({take:2});
  const made=await aisha.post("/api/v1/sets").send({title:"Authorization test set",description:"Private by default",outcome:"Build a study setup",budget:30000,items:p.map((x,i)=>({productId:x.id,slotName:i?"Power":"Computer",owned:i===0}))});
  privateSlug=made.body.set.slug;
  publicSlug=(await prisma.productSet.findFirstOrThrow({where:{visibility:"PUBLIC",owner:{email:{not:"rohan@completeit.local"}}}})).slug;
});
afterAll(()=>prisma.$disconnect());

describe("authentication and authorization",()=>{
  it("rejects a bad password",async()=>expect((await request(app).post("/api/v1/auth/login").send({email:"aisha@completeit.local",password:"bad"})).status).toBe(401));
  it("sets secure session cookies",async()=>{const r=await request(app).post("/api/v1/auth/login").send({email:"aisha@completeit.local",password:"CompleteIt@123"});expect(r.headers["set-cookie"].join(" ")).toContain("HttpOnly")});
  it("keeps password-reset account existence private",async()=>{const r=await request(app).post("/api/v1/auth/password-reset").send({email:"missing@completeit.local"});expect(r.status).toBe(200);expect(r.body.message).toContain("If that account exists")});
  it("protects private sets as not-found",async()=>expect((await rohan.get(`/api/v1/sets/${privateSlug}`)).status).toBe(404));
  it("lets owner see private set",async()=>expect((await aisha.get(`/api/v1/sets/${privateSlug}`)).status).toBe(200));
  it("does not expose unlisted or private sets in Explore",async()=>{const r=await request(app).get("/api/v1/explore");expect(r.body.sets.every((s:any)=>s.visibility==="PUBLIC")).toBe(true)});
});

describe("recommendation and community flow",()=>{
  it("creates a complete audit shape and three alternatives",async()=>{const r=await request(app).post("/api/v1/recommendations").set("x-guest-id","test-guest").send({outcome:"Build a study setup",budget:30000,ownedProductIds:[],detectedCategories:["laptops","desks","mice"],preference:"EITHER"});expect(r.status).toBe(201);expect(r.body.alternatives).toHaveLength(3);expect(r.body.audit).toMatchObject({completed:expect.any(Array),missingRequired:expect.any(Array),missingOptional:expect.any(Array),duplicates:expect.any(Array),incompatible:expect.any(Array)})});
  it("serves outcomes and product categories from the database",async()=>{const [outcomes,categories]=await Promise.all([request(app).get("/api/v1/outcomes"),request(app).get("/api/v1/product-categories")]);expect(outcomes.status).toBe(200);expect(outcomes.body.outcomes.every((value:any)=>value.templates.length>0)).toBe(true);expect(categories.body.categories.length).toBeGreaterThan(10)});
  it("uses the selected outcome template without falling back to laptops",async()=>{const r=await request(app).post("/api/v1/recommendations").set("x-guest-id","generic-test").send({outcome:"Organize a small room",budget:25000,ownedProductIds:[],detectedCategories:["storage"],preference:"EITHER"});expect(r.status).toBe(201);expect(r.body.template.name).toBe("Compact room layout");expect(r.body.recommendations.every((item:any)=>item.product.category.slug!=="laptops")).toBe(true)});
  it("accepts any custom outcome without recommending unrelated technology",async()=>{const r=await request(app).post("/api/v1/recommendations").set("x-guest-id","aquarium-test").send({outcome:"Maintain a clean aquarium",budget:3000,ownedProductIds:[],detectedCategories:["aquarium"],desiredCategories:["water-testing"],notes:"Weekly fish-tank cleaning and water testing",preference:"EITHER"});expect(r.status).toBe(201);expect(r.body.template).toMatchObject({name:"Custom completion plan",dynamic:true});expect(r.body.recommendations).toEqual([]);expect(r.body.audit.completed).toContain("Existing Aquarium")});
  it("uses diverse catalogue categories for a custom requested addition",async()=>{const r=await request(app).post("/api/v1/recommendations").set("x-guest-id","cycling-test").send({outcome:"Be ready for weekend bicycle trips",budget:5000,ownedProductIds:[],detectedCategories:[],desiredCategories:["cycling"],notes:"Add a cycling repair kit",preference:"EITHER"});expect(r.status).toBe(201);expect(r.body.recommendations.length).toBeGreaterThan(0);expect(r.body.recommendations.every((item:any)=>item.product.category.slug==="cycling")).toBe(true)});
  it("preserves non-catalogue products created manually",async()=>{const r=await aisha.post("/api/v1/sets").send({title:"Manual craft corner",description:"Custom products should remain attached.",outcome:"Organize a small room",budget:20000,manualItems:[{label:"Vintage sewing machine",category:"sewing equipment",brand:"Inherited",price:3500,owned:true}]});expect(r.status).toBe(201);const item=r.body.set.items.find((value:any)=>value.product.name==="Vintage sewing machine");expect(item.product).toMatchObject({custom:true,demo:false,verified:false,brand:"Inherited"});expect(item.owned).toBe(true)});
  it("forks privately and retains attribution",async()=>{const r=await rohan.post(`/api/v1/sets/${publicSlug}/fork`).send({});expect(r.status).toBe(201);expect(r.body.set.visibility).toBe("PRIVATE");const item=await prisma.productSetItem.findFirst({where:{setId:r.body.set.id}});expect(item?.attribution).toContain("Forked from")});
  it("publishes an owned set and exposes viewer ownership state",async()=>{const published=await aisha.post(`/api/v1/sets/${privateSlug}/publish`).send({visibility:"PUBLIC"});expect(published.status).toBe(200);expect(published.body.set).toMatchObject({visibility:"PUBLIC",status:"ACTIVE"});const detail=await aisha.get(`/api/v1/sets/${privateSlug}`);expect(detail.body.viewer).toMatchObject({isOwner:true,isFollowing:false})});
  it("follows and unfollows a set with accurate viewer and library state",async()=>{await rohan.post(`/api/v1/sets/${publicSlug}/follow`).send({});const [feed,library,detail]=await Promise.all([rohan.get("/api/v1/feed"),rohan.get("/api/v1/sets/mine"),rohan.get(`/api/v1/sets/${publicSlug}`)]);expect(feed.status).toBe(200);expect(Array.isArray(feed.body.events)).toBe(true);expect(library.body.following.some((set:any)=>set.slug===publicSlug)).toBe(true);expect(detail.body.viewer.isFollowing).toBe(true);expect((await rohan.delete(`/api/v1/sets/${publicSlug}/follow`)).body.isFollowing).toBe(false);const after=await rohan.get("/api/v1/sets/mine");expect(after.body.following.some((set:any)=>set.slug===publicSlug)).toBe(false)});
  it("creates a private copy without claiming it is a fork",async()=>{const copied=await rohan.post(`/api/v1/sets/${publicSlug}/copy`).send({});expect(copied.status).toBe(201);expect(copied.body.set).toMatchObject({visibility:"PRIVATE",status:"DRAFT",setType:"MANUAL"});expect(copied.body.set.items.every((item:any)=>item.attribution.includes("Copied from"))).toBe(true)});
  it("lets owners edit metadata and add then remove a catalogue product",async()=>{const product=await prisma.product.findFirstOrThrow({where:{setItems:{none:{set:{slug:privateSlug}}}}});const changed=await aisha.patch(`/api/v1/sets/${privateSlug}`).send({title:"Published authorization set",budget:42000});expect(changed.status).toBe(200);expect(changed.body.set).toMatchObject({title:"Published authorization set",budget:42000});const added=await aisha.post(`/api/v1/sets/${privateSlug}/items`).send({productId:product.id,slotName:"Owner addition",owned:false});expect(added.status).toBe(201);const item=added.body.set.items.find((value:any)=>value.productId===product.id);expect(item).toBeTruthy();const removed=await aisha.delete(`/api/v1/sets/${privateSlug}/items/${item.id}`);expect(removed.status).toBe(200);expect(removed.body.set.items.some((value:any)=>value.id===item.id)).toBe(false)});
  it("serves real profiles and toggles user, product and Product World follows",async()=>{const profile=await aisha.get("/api/v1/users/rohan");expect(profile.status).toBe(200);expect(profile.body.user).toMatchObject({username:"rohan",sets:expect.any(Array)});expect((await aisha.post("/api/v1/users/rohan/follow")).body.isFollowing).toBe(true);expect((await aisha.delete("/api/v1/users/rohan/follow")).body.isFollowing).toBe(false);const world=await prisma.productWorld.findFirstOrThrow();expect((await aisha.post(`/api/v1/product-worlds/${world.slug}/follow`)).body.isFollowing).toBe(true);const worldView=await aisha.get(`/api/v1/product-worlds/${world.slug}`);expect(worldView.body.viewer.isFollowing).toBe(true);expect((await aisha.delete(`/api/v1/product-worlds/${world.slug}/follow`)).body.isFollowing).toBe(false)});
});

describe("uploads",()=>{
  it("rejects non-image uploads",async()=>{const r=await request(app).post("/api/v1/uploads").attach("image",Buffer.from("not image"),{filename:"bad.txt",contentType:"text/plain"});expect(r.status).toBe(415)});
  it("sanitizes and stores a valid image in MinIO",async()=>{const png=Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=","base64");const r=await request(app).post("/api/v1/uploads").attach("image",png,{filename:"desk.png",contentType:"image/png"});expect(r.status).toBe(201);expect(r.body.upload).toMatchObject({mimeType:"image/jpeg",exifRemoved:true})});
  it("accepts a valid WebP even when the client reports a generic MIME type",async()=>{const webp=await sharp({create:{width:2,height:2,channels:3,background:"#7c3aed"}}).webp().toBuffer();const r=await request(app).post("/api/v1/uploads").attach("image",webp,{filename:"items.webp",contentType:"application/octet-stream"});expect(r.status).toBe(201);expect(r.body.upload).toMatchObject({mimeType:"image/jpeg",exifRemoved:true})});
  it("recognizes only the explicit photo fixture",async()=>{const fixture=await request(app).post("/api/v1/analysis").send({fixture:"desk-fixture",guestId:"photo-test"});expect(fixture.status).toBe(201);expect(fixture.body.session.objects.map((item:any)=>item.label)).toEqual(["Laptop","Desk","Mouse"]);expect(fixture.body.requiresManualConfirmation).toBe(false)});
  it("requires manual confirmation for arbitrary uploaded photos",async()=>{const arbitrary=await request(app).post("/api/v1/analysis").send({uploadId:undefined,guestId:"photo-test"});expect(arbitrary.status).toBe(201);expect(arbitrary.body.session.objects).toEqual([]);expect(arbitrary.body.requiresManualConfirmation).toBe(true)});
});
