import {describe,expect,it,vi} from "vitest";
import {analyzeImageWithVision,parseVisionPayload} from "../src/services/multimodalVisionService.js";

const inventory={sceneType:"packaged snacks on a table",confidence:.94,objects:[{label:"Pintola High Protein Oats",category:"Food and grocery",possibleBrand:"Pintola",possibleModel:null,visibleAttributes:["orange package","chocolate flavour","1 kg"],confidence:.97,evidence:"Front label clearly reads Pintola High Protein Oats"},{label:"uncertain reflection",category:"uncategorized",possibleBrand:null,possibleModel:null,visibleAttributes:[],confidence:.2,evidence:"Only a reflection is visible"}],suggestedOutcomes:["Build a high-protein pantry set"],missingInformation:["Expiry dates are not readable"]};

describe("portable multimodal image analysis",()=>{
  it("normalizes known categories and filters low-confidence guesses",()=>{const parsed=parseVisionPayload({output_text:JSON.stringify(inventory)},[{slug:"food-and-grocery",name:"Food and grocery"}]);expect(parsed.objects).toHaveLength(1);expect(parsed.objects[0]).toMatchObject({label:"Pintola High Protein Oats",category:"food-and-grocery",brand:"Pintola",attributes:{source:"multimodal-vision"}})});
  it("sends sanitized image bytes as a structured, non-stored vision request",async()=>{let body:any;const fetchImpl=vi.fn(async(_url:any,init:any)=>{body=JSON.parse(init.body);return new Response(JSON.stringify({output_text:JSON.stringify(inventory)}),{status:200,headers:{"content-type":"application/json"}})}) as any;const result=await analyzeImageWithVision(Buffer.from("sanitized-jpeg"),[{slug:"food-and-grocery",name:"Food and grocery"}],{apiKey:"test-key",baseUrl:"https://vision.example/v1",model:"vision-test",fetchImpl});expect(result?.objects[0]?.label).toBe("Pintola High Protein Oats");expect(body).toMatchObject({model:"vision-test",store:false,text:{format:{type:"json_schema",strict:true}}});expect(body.input[0].content[1].image_url).toMatch(/^data:image\/jpeg;base64,/)});
  it("supports Gemini structured vision for free-tier deployments",async()=>{let url="",body:any,headers:any;const fetchImpl=vi.fn(async(requestUrl:any,init:any)=>{url=String(requestUrl);body=JSON.parse(init.body);headers=init.headers;return new Response(JSON.stringify({candidates:[{content:{parts:[{text:JSON.stringify(inventory)}]}}]}),{status:200,headers:{"content-type":"application/json"}})}) as any;const result=await analyzeImageWithVision(Buffer.from("sanitized-jpeg"),[{slug:"food-and-grocery",name:"Food and grocery"}],{geminiApiKey:"gemini-test",geminiBaseUrl:"https://gemini.example/v1beta",geminiModel:"gemini-test-model",fetchImpl});expect(result?.objects[0]?.label).toBe("Pintola High Protein Oats");expect(url).toBe("https://gemini.example/v1beta/models/gemini-test-model:generateContent");expect(headers["x-goog-api-key"]).toBe("gemini-test");expect(body.generationConfig).toMatchObject({responseMimeType:"application/json",responseJsonSchema:{type:"object"}});expect(body.generationConfig.responseJsonSchema.properties.objects.maxItems).toBeUndefined();expect(body.contents[0].parts[0].inline_data).toMatchObject({mime_type:"image/jpeg"})});
  it("retries temporary Gemini capacity failures",async()=>{const fetchImpl=vi.fn().mockResolvedValueOnce(new Response("busy",{status:503})).mockResolvedValueOnce(new Response(JSON.stringify({candidates:[{content:{parts:[{text:JSON.stringify(inventory)}]}}]}),{status:200,headers:{"content-type":"application/json"}})) as any;const result=await analyzeImageWithVision(Buffer.from("sanitized-jpeg"),[],{geminiApiKey:"gemini-test",fetchImpl});expect(result?.provider).toBe("multimodal-vision");expect(fetchImpl).toHaveBeenCalledTimes(2)});
});
