import Link from "@/lib/navigation";
import {useRouter} from "@/lib/navigation";
import {useState} from "react";
import {Eye,EyeOff,LockKeyhole,Mail} from "lucide-react";
import {ActionLabel,ActivityIndicator,InlineFeedback,releaseActionFocus} from "@/components/action-feedback";
import {AuthShell} from "@/components/auth-shell";
import {api} from "@/lib/api";

export default function Login(){
  const router=useRouter();
  const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[showPassword,setShowPassword]=useState(false),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError("");try{await api("/auth/login",{method:"POST",body:JSON.stringify({email,password})});router.push("/my-sets")}catch(value){setError((value as Error).message)}finally{setBusy(false);releaseActionFocus()}}
  return <AuthShell eyebrow="Welcome back" title="Continue building" description="Log in to return to your sets, activity, and personalized discoveries."><form onSubmit={submit} className="mt-8 space-y-5"><label className="block"><span className="mb-2 block text-sm font-bold">Email</span><span className="relative block"><Mail className="pointer-events-none absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" size={18}/><input required autoComplete="email" placeholder="you@example.com" className="field !py-3.5 !pl-11" type="email" value={email} onChange={event=>setEmail(event.target.value)}/></span></label><div className="block"><label htmlFor="login-password" className="mb-2 block text-sm font-bold">Password</label><span className="relative block"><LockKeyhole className="pointer-events-none absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" size={18}/><input id="login-password" required autoComplete="current-password" placeholder="Enter your password" className="field !py-3.5 !pl-11 !pr-12" type={showPassword?"text":"password"} value={password} onChange={event=>setPassword(event.target.value)}/><button type="button" aria-label={showPassword?"Hide password":"Show password"} onClick={()=>setShowPassword(value=>!value)} className="absolute right-2 top-1/2 grid size-9 -translate-y-1/2 place-items-center rounded-lg text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800">{showPassword?<EyeOff size={18}/>:<Eye size={18}/>}</button></span></div><button disabled={busy} className="btn-primary !min-h-13 w-full"><ActionLabel busy={busy} busyText="Logging in…">Log in</ActionLabel></button>{busy&&<ActivityIndicator title="Opening your workspace" steps={["Checking your details…","Loading your private sets…"]}/>}<InlineFeedback message={error} tone="error"/></form><p className="mt-7 text-center text-sm text-slate-500">New to CompleteIt? <Link className="link" href="/register">Create an account</Link></p></AuthShell>;
}
