import argon2 from "argon2";
import {prisma} from "../config/prisma.js";
import {AppError} from "../errors/AppError.js";
import {hashToken,signAccess,signRefresh,verifyRefresh} from "../utils/tokens.js";
import {createSet} from "./setService.js";

export async function issueSession(user:{id:string,email:string}){const accessToken=await signAccess(user),refreshToken=await signRefresh(user);await prisma.user.update({where:{id:user.id},data:{refreshTokenHash:hashToken(refreshToken)}});return {accessToken,refreshToken};}
export async function register(input:any){if(await prisma.user.findFirst({where:{OR:[{email:input.email.toLowerCase()},{username:input.username.toLowerCase()}]}}))throw new AppError(409,"Email or username already exists","ACCOUNT_EXISTS");const user=await prisma.$transaction(async tx=>{const created=await tx.user.create({data:{email:input.email.toLowerCase(),username:input.username.toLowerCase(),passwordHash:await argon2.hash(input.password),profile:{create:{displayName:input.displayName}}}});if(input.guestDraft&&typeof input.guestDraft==="object"){const d=input.guestDraft as any;const selected=Array.isArray(d.productIds)?d.productIds:[];const objects=Array.isArray(d.objects)?d.objects:[];const exactIds=objects.flatMap((object:any)=>typeof object.productId==="string"?[object.productId]:[]);const itemIds=[...new Set([...selected,...exactIds])];const recommendationRows=Array.isArray(d.result?.recommendations)?d.result.recommendations:[];const items=itemIds.map(productId=>({productId,slotName:recommendationRows.find((row:any)=>row.product?.id===productId)?.slotName??(objects.find((object:any)=>object.productId===productId)?.owned===false?"Planned item":"Owned item"),owned:objects.find((object:any)=>object.productId===productId)?.owned!==false}));const manualItems=objects.filter((object:any)=>!object.productId&&object.label).map((object:any)=>({label:String(object.label).slice(0,120),category:String(object.category||"uncategorized").slice(0,80),brand:object.brand?String(object.brand).slice(0,80):undefined,price:Number(object.price)||0,slotName:object.owned===false?"Planned item":"Owned item",owned:object.owned!==false}));await createSet(created.id,{title:String(d.title||"My new set").slice(0,120),description:String(d.description||"Migrated from a guest recommendation session.").slice(0,2000),outcome:String(d.outcome||"Complete what I have").slice(0,120),budget:Number(d.budget)||0,visibility:"PRIVATE",templateId:d.result?.template?.id||undefined,items,manualItems},tx);}return created;});return {user,session:await issueSession(user)};}
export async function login(email:string,password:string){const user=await prisma.user.findUnique({where:{email:email.toLowerCase()},include:{profile:true}});if(!user||!await argon2.verify(user.passwordHash,password))throw new AppError(401,"Invalid email or password","INVALID_CREDENTIALS");return {user,session:await issueSession(user)};}
export async function rotate(refreshToken:string){const claims=await verifyRefresh(refreshToken).catch(()=>{throw new AppError(401,"Invalid refresh token","INVALID_REFRESH")});const user=await prisma.user.findUnique({where:{id:claims.userId}});if(!user||user.refreshTokenHash!==hashToken(refreshToken))throw new AppError(401,"Refresh token has already been rotated","REFRESH_REUSED");return {user,session:await issueSession(user)};}
