"use client";

import Link from "next/link";
import {useParams} from "next/navigation";
import {FormEvent,useEffect,useState} from "react";
import {useQuery,useQueryClient} from "@tanstack/react-query";
import {ArrowLeft,Plus,RefreshCw,Trash2} from "lucide-react";
import {api,money} from "@/lib/api";

export default function EditSet(){
  const {slug}=useParams<{slug:string}>(),queryClient=useQueryClient();
  const setQuery=useQuery({queryKey:["set",slug],queryFn:()=>api<any>(`/sets/${slug}`)}),productsQuery=useQuery({queryKey:["products"],queryFn:()=>api<any>("/products")});
  const [form,setForm]=useState({title:"",description:"",outcome:"",budget:0}),[newProduct,setNewProduct]=useState(""),[newSlot,setNewSlot]=useState("Planned addition"),[replacement,setReplacement]=useState<Record<string,string>>({}),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
  useEffect(()=>{const set=setQuery.data?.set;if(set)setForm({title:set.title,description:set.description,outcome:set.outcome,budget:set.budget})},[setQuery.data?.set]);
  async function change(path:string,method:string,body?:unknown,success="Set updated."){setBusy(true);setNotice("");try{const result=await api<any>(path,{method,body:body===undefined?undefined:JSON.stringify(body)});setNotice(success);await Promise.all([queryClient.invalidateQueries({queryKey:["set",slug]}),queryClient.invalidateQueries({queryKey:["my-sets"]})]);return result}catch(value){setNotice((value as Error).message)}finally{setBusy(false)}}
  async function save(event:FormEvent){event.preventDefault();await change(`/sets/${slug}`,"PATCH",form,"Set details saved.")}
  const data=setQuery.data,set=data?.set,products=productsQuery.data?.products??[];
  if(setQuery.isLoading)return <div className="skeleton h-[70vh]"/>;
  if(!set||!data.viewer?.isOwner)return <div className="panel mx-auto max-w-xl p-8 text-center"><h1 className="text-2xl font-black">Owner access required</h1><p className="mt-3 text-slate-500">Only the set owner can edit its products and details.</p><Link href={`/sets/${slug}`} className="link mt-5 inline-block">Back to set</Link></div>;
  return <div className="mx-auto max-w-4xl space-y-6"><Link href={`/sets/${slug}`} className="link inline-flex items-center gap-2"><ArrowLeft size={16}/>Back to set</Link><div><p className="eyebrow">Set editor</p><h1 className="display mt-2">Edit your set</h1><p className="mt-3 text-slate-500">Update the outcome and budget, add or remove products, or swap an item with a visible impact summary.</p></div>{notice&&<p role="status" className="rounded-xl bg-indigo-50 p-4 text-sm font-semibold text-indigo-800 dark:bg-indigo-950 dark:text-indigo-100">{notice}</p>}
    <form onSubmit={save} className="panel grid gap-4 p-6 sm:grid-cols-2"><h2 className="text-xl font-black sm:col-span-2">Set details</h2><label><span className="text-sm font-bold">Title</span><input aria-label="Set title" required minLength={3} className="field mt-1 w-full" value={form.title} onChange={event=>setForm(current=>({...current,title:event.target.value}))}/></label><label><span className="text-sm font-bold">Outcome</span><input aria-label="Set outcome" required className="field mt-1 w-full" value={form.outcome} onChange={event=>setForm(current=>({...current,outcome:event.target.value}))}/></label><label><span className="text-sm font-bold">Budget</span><input aria-label="Set budget" min="0" type="number" className="field mt-1 w-full" value={form.budget} onChange={event=>setForm(current=>({...current,budget:Number(event.target.value)}))}/></label><label className="sm:col-span-2"><span className="text-sm font-bold">Description</span><textarea aria-label="Set description" className="field mt-1 min-h-28 w-full" value={form.description} onChange={event=>setForm(current=>({...current,description:event.target.value}))}/></label><button disabled={busy} className="rounded-xl bg-indigo-600 px-5 py-2.5 font-bold text-white sm:col-span-2">Save details</button></form>
    <section className="space-y-3"><h2 className="text-xl font-black">Products</h2>{set.items.map((item:any)=><div className="panel grid gap-3 p-4 sm:grid-cols-[1fr_1fr_auto] sm:items-end" key={item.id}><div><span className="eyebrow">{item.slotName} · {item.owned?"owned":"planned"}</span><h3 className="mt-1 font-bold">{item.product.name}</h3><p className="text-sm text-slate-500">{item.product.brand} · {money(item.selectedPrice)}</p></div><label><span className="text-xs font-bold text-slate-500">Swap with</span><select aria-label={`Replacement for ${item.product.name}`} className="field mt-1 w-full" value={replacement[item.id]??""} onChange={event=>setReplacement(current=>({...current,[item.id]:event.target.value}))}><option value="">Choose replacement…</option>{products.filter((product:any)=>product.id!==item.productId).map((product:any)=><option value={product.id} key={product.id}>{product.name} · {money(product.price)}</option>)}</select></label><div className="flex gap-2"><button aria-label={`Swap ${item.product.name}`} disabled={busy||!replacement[item.id]} onClick={async()=>{const result=await change(`/sets/${slug}/swap`,"POST",{itemId:item.id,replacementId:replacement[item.id]},"Product swapped.");if(result)setNotice(`Swapped to ${result.after.name}. Price impact: ${result.impact.priceDifference>=0?"+":""}${money(result.impact.priceDifference)}; compatibility: ${String(result.impact.compatibilityDifference).toLowerCase().replaceAll("_"," ")}; space impact: ${result.impact.spaceImpact===null?"unknown":`${result.impact.spaceImpact} cm`}.`)}} type="button" className="rounded-xl border p-2.5 disabled:opacity-40"><RefreshCw size={17}/></button><button aria-label={`Remove ${item.product.name}`} disabled={busy} onClick={()=>change(`/sets/${slug}/items/${item.id}`,"DELETE",undefined,"Product removed.")} type="button" className="rounded-xl border p-2.5 text-red-600"><Trash2 size={17}/></button></div></div>)}</section>
    <form onSubmit={async event=>{event.preventDefault();const result=await change(`/sets/${slug}/items`,"POST",{productId:newProduct,slotName:newSlot,owned:false},"Product added.");if(result)setNewProduct("")}} className="panel grid gap-3 p-5 sm:grid-cols-[1fr_1fr_auto] sm:items-end"><label><span className="text-sm font-bold">Add catalogue product</span><select aria-label="Product to add" required className="field mt-1 w-full" value={newProduct} onChange={event=>setNewProduct(event.target.value)}><option value="">Choose product…</option>{products.map((product:any)=><option value={product.id} key={product.id}>{product.name} · {money(product.price)}</option>)}</select></label><label><span className="text-sm font-bold">Functional slot</span><input aria-label="New product slot" required className="field mt-1 w-full" value={newSlot} onChange={event=>setNewSlot(event.target.value)}/></label><button disabled={busy||!newProduct} className="flex items-center justify-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 font-bold text-white"><Plus size={17}/>Add</button></form>
  </div>;
}
