import {ErrorPanel} from "@/components/page-state"; import Link from "@/lib/navigation";
import {useState} from "react";
import {useQuery} from "@tanstack/react-query";
import {ArrowRight,PackageSearch,Search as SearchIcon,SlidersHorizontal,UsersRound} from "lucide-react";
import {api,money} from "@/lib/api";
import {SetCard} from "@/components/set-card";
import {ActivityIndicator} from "@/components/action-feedback";
import {track} from "@/lib/analytics";

const examples=["Weekend cycling essentials","Balcony gardening under ₹5,000","Travel photography kit","Cooking basics","Pet care","Anything for a camping trip"];
const emptyFilters={budget:"",setType:"",minSlots:"",minRating:"",minOutcome:"",minUsage:""};

export default function Search(){
  const [input,setInput]=useState(""),[q,setQ]=useState(""),[filters,setFilters]=useState(emptyFilters),[hasSearched,setHasSearched]=useState(false);
  const params=new URLSearchParams({q});Object.entries(filters).forEach(([key,value])=>value&&params.set(key,value));
  const hasCriteria=Boolean(q.trim()||Object.values(filters).some(Boolean));
  const {data,isFetching,error,refetch}=useQuery({queryKey:["search",q,filters],queryFn:()=>api<any>(`/search?${params}`),enabled:hasSearched&&hasCriteria});
  const total=(data?.sets?.length??0)+(data?.products?.length??0)+(data?.users?.length??0)+(data?.topics?.length??0);
  function change(key:string,value:string){setFilters(current=>({...current,[key]:value}))}
  function search(value=input){const query=value.trim();setInput(value);setQ(query);setHasSearched(true);track("search_submitted",{queryLength:query.length,hasFilters:Object.values(filters).some(Boolean)})}
  return <div>
    <section className="mx-auto max-w-4xl text-center"><h1 className="display mt-4">Find the missing piece.</h1><p className="mx-auto mt-5 max-w-2xl text-lg leading-relaxed text-slate-500">Search any product, goal, person, or collection. Describe the outcome you want—not just a category.</p><form className="search-form panel relative mx-auto mt-8 max-w-3xl p-2" onSubmit={event=>{event.preventDefault();search()}}><SearchIcon className="absolute left-6 top-1/2 -translate-y-1/2 text-slate-400" size={21}/><input aria-label="Search" className="w-full rounded-2xl bg-transparent py-4 pl-12 pr-32 text-base outline-none placeholder:text-slate-400" value={input} onChange={event=>setInput(event.target.value)} placeholder="What are you trying to complete?"/><button className="btn-primary absolute right-2 top-2 !min-h-[3rem]">Search <ArrowRight size={16}/></button></form><div className="mt-4 flex flex-wrap justify-center gap-2">{examples.map(value=><button type="button" onClick={()=>search(value)} className="chip hover:!border-indigo-300 hover:!text-indigo-600" key={value}>{value}</button>)}</div></section>
    <details className="panel mx-auto mt-7 max-w-5xl p-5"><summary className="flex cursor-pointer items-center gap-2 font-black"><span className="grid size-9 place-items-center rounded-xl bg-indigo-50 text-indigo-600 dark:bg-indigo-950 dark:text-indigo-300"><SlidersHorizontal size={17}/></span>Fine-tune results</summary><div className="mt-5 grid gap-3 sm:grid-cols-3 lg:grid-cols-6"><Filter label="Maximum budget"><input aria-label="Maximum budget" className="field" type="number" min="0" value={filters.budget} onChange={event=>change("budget",event.target.value)}/></Filter><Filter label="Set type"><select aria-label="Set type" className="field" value={filters.setType} onChange={event=>change("setType",event.target.value)}><option value="">Any</option><option value="OFFICIAL">Official</option><option value="MIXED">Mixed</option><option value="COMMUNITY">Community</option><option value="MANUAL">Manual</option><option value="FORK">Fork</option></select></Filter><Filter label="Completion"><input aria-label="Minimum slot completion" className="field" type="number" min="1" max="100" value={filters.minSlots} onChange={event=>change("minSlots",event.target.value)}/></Filter><Filter label="Rating"><input aria-label="Minimum community rating" className="field" type="number" min="1" max="5" step="0.5" value={filters.minRating} onChange={event=>change("minRating",event.target.value)}/></Filter><Filter label="Goal fit"><input aria-label="Minimum outcome success" className="field" type="number" min="1" max="100" value={filters.minOutcome} onChange={event=>change("minOutcome",event.target.value)}/></Filter><Filter label="Days used"><input aria-label="Minimum usage days" className="field" type="number" min="1" value={filters.minUsage} onChange={event=>change("minUsage",event.target.value)}/></Filter></div><button type="button" onClick={()=>setFilters(emptyFilters)} className="link mt-4 text-sm">Clear all filters</button></details>
    {isFetching&&<div className="mx-auto mt-6 max-w-3xl"><ActivityIndicator title="Searching across CompleteIt" steps={["Scanning goals and set titles…","Matching products and people…","Ranking the most useful results…"]}/></div>}
    {!hasSearched&&<div className="empty-state mx-auto mt-10 max-w-2xl"><PackageSearch className="mx-auto text-indigo-500" size={36}/><h2 className="mt-4 text-xl font-black">Search starts when you are ready</h2><p className="mt-2 text-sm text-slate-500">Enter a goal or choose an example. CompleteIt will only load the results you ask for.</p></div>}
    {error&&<ErrorPanel error={error} onRetry={refetch}/>} {hasSearched&&!hasCriteria&&<p role="status" className="empty-state mt-6">Enter a search or choose a filter to find matching results.</p>} {data&&!error&&<div className="mt-14 space-y-16"><div className="flex items-center justify-between"><span className="chip">{total} found</span></div>{data.sets?.length>0&&<ResultSection icon={PackageSearch} title="Sets" count={data.sets.length}><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{data.sets.map((set:any)=><SetCard set={set} key={set.id}/>)}</div></ResultSection>}{data.products?.length>0&&<ResultSection icon={PackageSearch} title="Products" count={data.products.length}><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{data.products.map((product:any)=><Link href={`/products/${product.id}`} className="panel group p-5" key={product.id}><span className="eyebrow">{product.category.name}</span><h3 className="mt-2 font-black group-hover:text-indigo-600">{product.name}</h3><p className="mt-1 text-sm text-slate-500">{product.brand}</p><b className="mt-5 block text-lg">{money(product.price)}</b></Link>)}</div></ResultSection>}<div className="grid gap-10 lg:grid-cols-2"><ResultList icon={UsersRound} title="People" rows={data.users?.map((user:any)=>({href:`/users/${user.username}`,title:user.profile?.displayName??user.username,detail:`@${user.username} · ${user._count.sets} public sets`}))}/><ResultList icon={SlidersHorizontal} title="Topics" rows={data.topics?.map((topic:any)=>({title:topic.name,detail:topic.description}))}/></div>{total===0&&<div className="empty-state"><SearchIcon className="mx-auto text-slate-400" size={36}/><h2 className="mt-4 text-xl font-black">No exact matches yet</h2><p className="mt-2 text-sm text-slate-500">Try describing the outcome in fewer words or clear the optional filters.</p></div>}</div>}
  </div>;
}

function Filter({label,children}:{label:string;children:React.ReactNode}){return <label><span className="mb-1.5 block text-xs font-bold text-slate-500">{label}</span>{children}</label>}
function ResultSection({icon:Icon,title,count,children}:{icon:any;title:string;count:number;children:React.ReactNode}){return <section><div className="mb-6 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-indigo-50 text-indigo-600 dark:bg-indigo-950 dark:text-indigo-300"><Icon size={18}/></span><h2 className="text-2xl font-black">{title}</h2><span className="text-lg font-black text-slate-300">{count}</span></div>{children}</section>}
function ResultList({icon:Icon,title,rows=[]}:{icon:any;title:string;rows?:Array<{href?:string;title:string;detail:string}>}){
  return <section><div className="mb-5 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-indigo-50 text-indigo-600 dark:bg-indigo-950 dark:text-indigo-300"><Icon size={18}/></span><h2 className="text-2xl font-black">{title}</h2><span className="text-lg font-black text-slate-300">{rows.length}</span></div><div className="grid gap-3">{rows.map((row,index)=>row.href?<Link href={row.href} className="panel group flex items-center justify-between p-5" key={`${row.href}-${index}`}><span><b>{row.title}</b><p className="mt-1 text-sm text-slate-500">{row.detail}</p></span><ArrowRight className="text-slate-300 transition group-hover:translate-x-1 group-hover:text-indigo-500" size={17}/></Link>:<div className="panel p-5" key={`${row.title}-${index}`}><b>{row.title}</b><p className="mt-1 text-sm text-slate-500">{row.detail}</p></div>)}</div></section>
}
