import Link from "@/lib/navigation";
import {useRouter} from "@/lib/navigation";
import {useEffect,useState} from "react";
import {Eye,EyeOff,LockKeyhole,Mail,UserRound} from "lucide-react";
import {ActionLabel,ActivityIndicator,InlineFeedback,releaseActionFocus} from "@/components/action-feedback";
import {AuthShell} from "@/components/auth-shell";
import {api} from "@/lib/api";

export default function Register(){
  const router=useRouter();
  const [migrate,setMigrate]=useState(false),[showPassword,setShowPassword]=useState(false),[form,setForm]=useState({displayName:"",username:"",email:"",password:""}),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  useEffect(()=>setMigrate(new URLSearchParams(location.search).get("migrate")==="1"),[]);
  function change(key:keyof typeof form,value:string){setForm(current=>({...current,[key]:value}))}
  async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError("");try{const guestDraft=migrate?JSON.parse(localStorage.getItem("completeit-guest-draft")??"null"):undefined;await api("/auth/register",{method:"POST",body:JSON.stringify({...form,guestDraft})});localStorage.removeItem("completeit-guest-draft");router.push("/my-sets")}catch(value){setError((value as Error).message)}finally{setBusy(false);releaseActionFocus()}}
  return <AuthShell eyebrow="Create your space" title={migrate?"Save your set":"Start completing"} description="A free account keeps your sets organized, private when you want, and ready to improve.">{migrate&&<div className="mt-5 rounded-2xl border border-indigo-200 bg-indigo-50 p-4 text-sm font-semibold text-indigo-800 dark:border-indigo-900 dark:bg-indigo-950/40 dark:text-indigo-100">Your temporary set is ready. It will move into My Sets after signup and stay private.</div>}<form className="mt-7 grid gap-4 sm:grid-cols-2" onSubmit={submit}><Field id="register-display-name" label="Display name" icon={UserRound}><input required minLength={2} id="register-display-name" autoComplete="name" className="field !pl-11" placeholder="Your name" value={form.displayName} onChange={event=>change("displayName",event.target.value)}/></Field><Field id="register-username" label="Username" icon={UserRound}><input required minLength={2} id="register-username" autoComplete="username" className="field !pl-11" placeholder="choose-a-username" value={form.username} onChange={event=>change("username",event.target.value)}/></Field><div className="sm:col-span-2"><Field id="register-email" label="Email" icon={Mail}><input required id="register-email" autoComplete="email" className="field !pl-11" type="email" placeholder="you@example.com" value={form.email} onChange={event=>change("email",event.target.value)}/></Field></div><div className="sm:col-span-2"><Field id="register-password" label="Password" icon={LockKeyhole}><input required minLength={8} id="register-password" autoComplete="new-password" className="field !pl-11 !pr-12" type={showPassword?"text":"password"} placeholder="At least 8 characters" value={form.password} onChange={event=>change("password",event.target.value)}/><button type="button" aria-label={showPassword?"Hide password":"Show password"} onClick={()=>setShowPassword(value=>!value)} className="absolute right-2 top-1/2 grid size-9 -translate-y-1/2 place-items-center rounded-lg text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800">{showPassword?<EyeOff size={18}/>:<Eye size={18}/>}</button></Field></div><button disabled={busy} className="btn-primary !min-h-13 sm:col-span-2"><ActionLabel busy={busy} busyText="Creating your account…">Create account</ActionLabel></button>{busy&&<div className="sm:col-span-2"><ActivityIndicator title={migrate?"Creating your account and saving the set":"Creating your account"} steps={["Securing your details…",migrate?"Moving your private draft…":"Preparing your library…"]}/></div>}<div className="sm:col-span-2"><InlineFeedback message={error} tone="error"/></div></form><p className="mt-6 text-center text-sm text-slate-500">Already registered? <Link className="link" href="/login">Log in</Link></p></AuthShell>;
}

function Field({id,label,icon:Icon,children}:{id:string;label:string;icon:any;children:React.ReactNode}){return <div className="block"><label htmlFor={id} className="mb-2 block text-sm font-bold">{label}</label><span className="relative block"><Icon className="pointer-events-none absolute left-3.5 top-1/2 z-10 -translate-y-1/2 text-slate-400" size={18}/>{children}</span></div>}
