import type {RequestHandler} from "express";
import {prisma} from "../config/prisma.js";
export const listProducts:RequestHandler=async(req,res)=>{const q=String(req.query.q??"");const products=await prisma.product.findMany({where:q?{OR:[{name:{contains:q,mode:"insensitive"}},{brand:{contains:q,mode:"insensitive"}},{category:{name:{contains:q,mode:"insensitive"}}}]}:{},include:{category:true},orderBy:[{category:{name:"asc"}},{name:"asc"}],take:250});res.json({notice:"Demo product information — live merchant data is not connected.",products});};
export const listCategories:RequestHandler=async(_req,res)=>res.json({categories:await prisma.productCategory.findMany({include:{_count:{select:{products:true}}},orderBy:{name:"asc"}})});
export const getProduct:RequestHandler=async(req,res)=>{const product=await prisma.product.findUnique({where:{id:String(req.params.id)},include:{category:true,images:true,worlds:true,_count:{select:{follows:true}}}});const isFollowing=Boolean(product&&req.auth&&await prisma.productFollow.findUnique({where:{userId_productId:{userId:req.auth.userId,productId:product.id}}}));res.json({product,viewer:{authenticated:Boolean(req.auth),isFollowing}})};
export const listOutcomes:RequestHandler=async(_req,res)=>res.json({outcomes:await prisma.outcome.findMany({include:{templates:{include:{slots:true}}}})});
export const listTopics:RequestHandler=async(req,res)=>{const topics=await prisma.topic.findMany({include:{_count:{select:{follows:true}}},orderBy:{name:"asc"}});const followed=req.auth?await prisma.topicFollow.findMany({where:{userId:req.auth.userId},select:{topicId:true}}):[];const followedIds=new Set(followed.map(value=>value.topicId));res.json({topics:topics.map(topic=>({...topic,isFollowing:followedIds.has(topic.id)})),viewer:{authenticated:Boolean(req.auth)}})};
export const listWorlds:RequestHandler=async(_req,res)=>{const worlds=await prisma.productWorld.findMany({include:{product:{include:{category:true,_count:{select:{follows:true}}}}}});res.json({worlds:worlds.map(world=>({...world,followers:world.product._count.follows})).sort((a,b)=>b.followers-a.followers)});};
export const getWorld:RequestHandler=async(req,res)=>{const world=await prisma.productWorld.findUnique({where:{slug:String(req.params.slug)},include:{product:{include:{category:true,_count:{select:{follows:true}}}}}});const [sets,follow]=world?await Promise.all([prisma.productSet.findMany({where:{visibility:"PUBLIC",OR:[{anchorProductId:world.productId},{items:{some:{productId:world.productId}}}]},include:{owner:{select:{username:true,profile:true}},items:{include:{product:true}}},orderBy:{communityRating:"desc"}}),req.auth?prisma.productFollow.findUnique({where:{userId_productId:{userId:req.auth.userId,productId:world.productId}}}):null]):[[],null];res.json({world:world?{...world,followers:world.product._count.follows}:null,viewer:{authenticated:Boolean(req.auth),isFollowing:Boolean(follow)},sets});};
