"use client";
import Link from "next/link";
import {useParams,useRouter} from "next/navigation";
import {useState} from "react";
import {useQuery,useQueryClient} from "@tanstack/react-query";
import {Globe2,Heart} from "lucide-react";
import {api,money} from "@/lib/api";
import {SetCard} from "@/components/set-card";

export default function ProductWorld(){const {slug}=useParams<{slug:string}>(),router=useRouter(),queryClient=useQueryClient(),[notice,setNotice]=useState("");const {data,isLoading}=useQuery({queryKey:["world",slug],queryFn:()=>api<any>(`/product-worlds/${slug}`)});if(isLoading)return <div className="skeleton h-96"/>;if(!data?.world)return <h1>Product World not found</h1>;const world=data.world;async function toggle(){try{await api(`/product-worlds/${slug}/follow`,{method:data.viewer.isFollowing?"DELETE":"POST"});setNotice(data.viewer.isFollowing?"Product World unfollowed.":"Product World followed.");await Promise.all([queryClient.invalidateQueries({queryKey:["world",slug]}),queryClient.invalidateQueries({queryKey:["worlds"]})])}catch(value){if(/auth|session/i.test((value as Error).message))router.push("/login");else setNotice((value as Error).message)}}return <div><section className="rounded-[2rem] bg-gradient-to-br from-indigo-950 to-indigo-600 p-8 text-white sm:p-12"><Globe2 size={38}/><p className="mt-8 text-sm font-bold uppercase tracking-wider text-indigo-200">Product World</p><h1 className="mt-2 text-4xl font-black sm:text-5xl">{world.title}</h1><p className="mt-4 max-w-2xl text-indigo-100">{world.description}</p>{notice&&<p role="status" className="mt-4 text-sm font-semibold text-white">{notice}</p>}<div className="mt-8 flex flex-wrap gap-3"><button onClick={toggle} className="flex items-center gap-2 rounded-xl bg-white px-4 py-2.5 font-bold text-indigo-800"><Heart size={18} fill={data.viewer.isFollowing?"currentColor":"none"}/>{data.viewer.isFollowing?"Unfollow":"Follow"} World · {world.followers}</button><Link href={`/products/${world.product.id}`} className="chip !border-white/20 !bg-white/10 !text-white">{world.product.brand} · {money(world.product.price)}</Link></div></section><div className="mt-10 grid gap-6 sm:grid-cols-3">{[["Official-brand sets","Same-brand options appear only with seeded evidence."],["Mixed-brand sets","Budget-conscious combinations across brands."],["Community-proven sets","Ranked with usage duration and outcome updates."]].map(([title,body])=><div className="panel p-5" key={title}><h2 className="font-bold">{title}</h2><p className="mt-2 text-sm text-slate-500">{body}</p></div>)}</div><section className="mt-12"><h2 className="text-2xl font-black">Sets containing this anchor</h2><div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{data.sets.map((set:any)=><SetCard set={set} key={set.id}/>)}</div>{data.sets.length===0&&<p className="mt-4 text-slate-500">No public sets yet. <Link href={`/create?anchor=${world.product.id}`} className="link">Create the first one from this product.</Link></p>}</section></div>}
