"use client";

import {useState} from "react";
import {Download,Shield,Trash2} from "lucide-react";
import {ActionLabel,ActivityIndicator,InlineFeedback,releaseActionFocus} from "@/components/action-feedback";
import {API,api} from "@/lib/api";

export default function Settings(){
  const [notice,setNotice]=useState(""),[tone,setTone]=useState<"success"|"error">("success"),[busy,setBusy]=useState<"export"|"delete"|"">("");
  async function exportData(){setBusy("export");setNotice("");try{const res=await fetch(`${API}/users/me/export`,{credentials:"include"});if(!res.ok)throw new Error("Log in before exporting your data.");const blob=await res.blob(),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="completeit-export.json";a.click();URL.revokeObjectURL(url);setTone("success");setNotice("Your export was downloaded.")}catch(value){setTone("error");setNotice((value as Error).message)}finally{setBusy("");releaseActionFocus()}}
  async function deleteAccount(){if(!confirm("Permanently delete your local CompleteIt account and all owned sets?")){releaseActionFocus();return}setBusy("delete");setNotice("");try{await api("/users/me",{method:"DELETE"});location.href="/"}catch(value){setTone("error");setNotice((value as Error).message);setBusy("");releaseActionFocus()}}
  return <div className="mx-auto max-w-3xl"><p className="eyebrow">Account & privacy</p><h1 className="display mt-3">Settings</h1><section className="panel mt-8 p-6"><div className="flex gap-4"><Shield className="text-indigo-600"/><div><h2 className="font-bold">Publishing privacy</h2><p className="mt-2 text-sm leading-relaxed text-slate-500">New sets and migrated guest drafts are private. Before publishing room images, inspect faces, addresses, documents, bills, screens and valuables. Server processing removes EXIF metadata.</p></div></div></section><section className="panel mt-4 divide-y dark:divide-slate-700"><div><button disabled={Boolean(busy)} onClick={exportData} className="flex w-full items-center gap-4 p-5 text-left disabled:opacity-60"><Download/><span><b className="block"><ActionLabel busy={busy==="export"} busyText="Preparing your export…">Export my data</ActionLabel></b><small className="text-slate-500">Download profile, sets and activity as JSON.</small></span></button>{busy==="export"&&<div className="px-5 pb-5"><ActivityIndicator title="Preparing your private data export" steps={["Collecting your profile…","Collecting sets and activity…"]}/></div>}{busy!=="delete"&&<InlineFeedback message={notice} tone={tone} className="mx-5 mb-5"/>}</div><div><button disabled={Boolean(busy)} onClick={deleteAccount} className="flex w-full items-center gap-4 p-5 text-left text-red-600 disabled:opacity-60"><Trash2/><span><b className="block"><ActionLabel busy={busy==="delete"} busyText="Deleting account…">Delete account</ActionLabel></b><small>This cannot be undone.</small></span></button>{busy==="delete"&&<div className="px-5 pb-5"><ActivityIndicator title="Deleting your account" steps={["Removing private sets and activity…","Finishing securely…"]}/></div>}</div></section></div>;
}
